# Generated by Django 5.1.7 on 2025-03-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengguna',
            name='tanggal_join',
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='address_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
