# Generated by Django 5.1.7 on 2025-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_remove_pengguna_tanggal_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='tanggal_join',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='address_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='city',
            field=models.CharField(help_text='Enter your city', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='zip_code',
            field=models.CharField(max_length=7),
        ),
    ]
